
Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1

Using base prefix '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3'
New python executable in /localscratch/shibin2.30537241.0/env/bin/python
Installing setuptools, pip, wheel...done.
Ignoring pip: markers 'python_version < "3"' don't match your environment
Collecting pip
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-18.1
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting numpy==1.16.3
Installing collected packages: numpy
Successfully installed numpy-1.16.3
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting tensorboard==1.14.0
Collecting setuptools>=41.0.0 (from tensorboard==1.14.0)
Collecting markdown>=2.6.8 (from tensorboard==1.14.0)
Collecting absl-py>=0.4 (from tensorboard==1.14.0)
Collecting protobuf>=3.6.0 (from tensorboard==1.14.0)
Requirement already satisfied: numpy>=1.12.0 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorboard==1.14.0) (1.16.3)
Collecting werkzeug>=0.11.15 (from tensorboard==1.14.0)
Collecting grpcio>=1.6.3 (from tensorboard==1.14.0)
Collecting six>=1.10.0 (from tensorboard==1.14.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorboard==1.14.0) (0.29.0)
Installing collected packages: setuptools, markdown, six, absl-py, protobuf, werkzeug, grpcio, tensorboard
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed absl-py-0.7.1 grpcio-1.25.0 markdown-3.2 protobuf-3.11.3 setuptools-41.6.0 six-1.14.0 tensorboard-1.14.0 werkzeug-1.0.1
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting tensorflow_gpu==1.15.0
Requirement already satisfied: absl-py>=0.7.0 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow_gpu==1.15.0) (0.7.1)
Requirement already satisfied: grpcio>=1.8.6 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow_gpu==1.15.0) (1.25.0)
Collecting opt-einsum>=2.3.2 (from tensorflow_gpu==1.15.0)
Requirement already satisfied: six>=1.10.0 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow_gpu==1.15.0) (1.14.0)
Collecting tensorboard<1.16.0,>=1.15.0 (from tensorflow_gpu==1.15.0)
Collecting gast==0.2.2 (from tensorflow_gpu==1.15.0)
Collecting google-pasta>=0.1.6 (from tensorflow_gpu==1.15.0)
Collecting keras-preprocessing>=1.0.5 (from tensorflow_gpu==1.15.0)
Requirement already satisfied: protobuf>=3.6.1 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow_gpu==1.15.0) (3.11.3)
Collecting termcolor>=1.1.0 (from tensorflow_gpu==1.15.0)
Requirement already satisfied: wheel>=0.26 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow_gpu==1.15.0) (0.29.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow_gpu==1.15.0) (1.16.3)
Collecting astor>=0.6.0 (from tensorflow_gpu==1.15.0)
Collecting tensorflow-estimator==1.15.1 (from tensorflow_gpu==1.15.0)
Collecting wrapt>=1.11.1 (from tensorflow_gpu==1.15.0)
Collecting keras-applications>=1.0.8 (from tensorflow_gpu==1.15.0)
Requirement already satisfied: setuptools>=41.0.0 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow_gpu==1.15.0) (41.6.0)
Requirement already satisfied: markdown>=2.6.8 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow_gpu==1.15.0) (3.2)
Requirement already satisfied: werkzeug>=0.11.15 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow_gpu==1.15.0) (1.0.1)
Collecting h5py (from keras-applications>=1.0.8->tensorflow_gpu==1.15.0)
Installing collected packages: opt-einsum, tensorboard, gast, google-pasta, keras-preprocessing, termcolor, astor, tensorflow-estimator, wrapt, h5py, keras-applications, tensorflow-gpu
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
Successfully installed astor-0.8.1 gast-0.2.2 google-pasta-0.1.8 h5py-2.10.0 keras-applications-1.0.8 keras-preprocessing-1.1.0 opt-einsum-2.3.2 tensorboard-1.15.0 tensorflow-estimator-1.15.1 tensorflow-gpu-1.15.0 termcolor-1.1.0 wrapt-1.11.2
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting tensorflow-estimator==1.14.0
tensorflow-gpu 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 1.14.0 which is incompatible.
Installing collected packages: tensorflow-estimator
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
Successfully installed tensorflow-estimator-1.14.0
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /home/shibin2/projects/def-ajbonner/shibin2/tensorflow_probability-0.7.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.13.3 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow-probability==0.7.0) (1.16.3)
Collecting cloudpickle>=0.6.1 (from tensorflow-probability==0.7.0)
Requirement already satisfied: six>=1.10.0 in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from tensorflow-probability==0.7.0) (1.14.0)
Collecting decorator (from tensorflow-probability==0.7.0)
Installing collected packages: cloudpickle, decorator, tensorflow-probability
Successfully installed cloudpickle-1.3.0 decorator-4.4.2 tensorflow-probability-0.7.0
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting imageio==2.4.1
Requirement already satisfied: numpy in /local/shibin2.30537241.0/env/lib/python3.6/site-packages (from imageio==2.4.1) (1.16.3)
Collecting pillow (from imageio==2.4.1)
Installing collected packages: pillow, imageio
Successfully installed imageio-2.4.1 pillow-7.0.0
W0416 13:17:11.150619 47482437840576 deprecation.py:506] From /localscratch/shibin2.30537241.0/env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0416 13:17:12.334016 47482437840576 deprecation.py:506] From /localscratch/shibin2.30537241.0/env/lib/python3.6/site-packages/tensorflow_core/python/training/rmsprop.py:119: calling Ones.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0416 13:17:19.086375 47482437840576 deprecation.py:323] From /home/shibin2/projects/def-ajbonner/shibin2/code/train_variational_autoencoder_tensorflow_circle83.py:205: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
2020-04-16 13:17:39.866265: E tensorflow/stream_executor/cuda/ptxas_utils.cc:110] You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 9.2.88).  Compilation of XLA kernels below will likely fail.

You do not need to update CUDA; cherry-picking the ptxas binary is sufficient.
W0416 13:17:42.508920 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 13:17:42.525621 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 13:17:42.539211 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 13:40:59.946173 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 13:41:00.051584 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 13:41:00.064935 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:04:13.699770 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:04:13.746517 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:04:13.757663 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:24:58.454497 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:24:58.468954 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:24:58.477702 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:46:02.054832 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:46:02.073468 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 14:46:02.082392 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:06:58.383582 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:06:58.405693 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:06:58.418200 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:27:37.192853 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:27:39.114585 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:27:43.475401 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:48:22.141161 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:48:22.341709 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 15:48:22.771373 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 16:08:34.614901 47482437840576 util.py:61] Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 16:08:34.633085 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
W0416 16:08:34.646930 47482437840576 util.py:61] Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
slurmstepd: error: *** JOB 30537241 ON gra871 CANCELLED AT 2020-04-16T16:16:36 DUE TO TIME LIMIT ***
